local M = {
	{id = 1,range = 1,name = "饕餮盛宴",icon = "",hurt = 1,cd = 1},
	{id = 2,range = 1,name = "燕返",icon = "",hurt = 1,cd = 1},
	{id = 3,range = 1,name = "反击",icon = "",hurt = 1,cd = 1},
	{id = 4,range = 1,name = "敬神",icon = "",hurt = 1,cd = 1},
	{id = 5,range = 1,name = "邪眼",icon = "",hurt = 1,cd = 1},
	{id = 6,range = 1,name = "返祖",icon = "",hurt = 1,cd = 1},
	{id = 7,range = 1,name = "敬神",icon = "",hurt = 1,cd = 1},
	{id = 8,range = 1,name = "怜悯",icon = "",hurt = 1,cd = 1},
	{id = 9,range = 1,name = "邪眼",icon = "",hurt = 1,cd = 1},
	{id = 10,range = 1,name = "真实",icon = "",hurt = 1,cd = 1},
	{id = 11,range = 1,name = "信仰",icon = "",hurt = 1,cd = 1},
	{id = 12,range = 1,name = "安息",icon = "",hurt = 1,cd = 1},
	{id = 13,range = 1,name = "忍耐",icon = "",hurt = 1,cd = 1},
	{id = 14,range = 1,name = "无欲",icon = "",hurt = 1,cd = 1},
	{id = 15,range = 1,name = "戒杀",icon = "",hurt = 1,cd = 1},
	{id = 16,range = 1,name = "沉默",icon = "",hurt = 1,cd = 1},
	{id = 17,range = 1,name = "纯洁",icon = "",hurt = 1,cd = 1},
	{id = 18,range = 1,name = "慈爱",icon = "",hurt = 1,cd = 1},
	{id = 19,range = 1,name = "霸者",icon = "",hurt = 1,cd = 1},
	{id = 20,range = 1,name = "万象天引",icon = "",hurt = 1,cd = 1},
	{id = 21,range = 1,name = "神罗天征",icon = "",hurt = 1,cd = 1},
	{id = 22,range = 1,name = "螺旋丸",icon = "",hurt = 1,cd = 1},
	{id = 23,range = 1,name = "十字军的远征",icon = "",hurt = 1,cd = 1},
	{id = 24,range = 1,name = "如影随形",icon = "",hurt = 1,cd = 1},
	{id = 25,range = 1,name = "天降正义",icon = "",hurt = 1,cd = 1},
	{id = 26,range = 1,name = "英雄不朽",icon = "",hurt = 1,cd = 1},
	{id = 27,range = 1,name = "无心天使",icon = "",hurt = 1,cd = 1},
	{id = 28,range = 1,name = "信仰之跃",icon = "",hurt = 1,cd = 1},
	{id = 29,range = 1,name = "不洁狂热",icon = "",hurt = 1,cd = 1},
	{id = 30,range = 1,name = "封魔领域",icon = "",hurt = 1,cd = 1},
}

return M